### PR TITLE
Actions are really just filters

### PR DESCRIPTION
**Pull request by szepeviktor**
from WP core:
```php
function add_action( $tag, $function_to_add, $priority = 10, $accepted_args = 1 ) {
    return add_filter( $tag, $function_to_add, $priority, $accepted_args );
}
```

😿

### CODE REVIEW

**Comment by widoz** [comment]
Hi @szepeviktor,

Thanks for the Pr, I know actions are just filters I wanted to keep them separately because I thought what if WordPress do some change and internally actions will get some additional logic?

That being said, I my self choosen to do not thread them differently in my abstractions and always return from the dispatcher, the actions will return `null` (and I think null is still a value) so I support your idea of adding just filters.

What about `HookType` and `HookTypeAwareRemover` can be removed too.

I would like to hear your opinion

**Comment by szepeviktor** [comment]
TBH I do not understand 100% what your code does.
This PR is for making phpstan more popular.

**Comment by szepeviktor** [comment]
Ooop, there is no mention on @phpstan in the top comment :)

**Comment by widoz** [comment]
> > what if WordPress do some change and internally actions will get some additional logic?
> 
> I think that is not possible as core is almost PHP 4 compatible, although Automattic recently writes namespaced PHP code!

I would like to see the commits in WordPress to understand how th code changed and why them are the same thing now. 

Btw as far as I see the `WP_Hook` does not define a method `add_action` and the `do_action` it is just a wrapper for `apply_filters`

I think I'll remove completely the concept of types in the implementation and just define filters.
Will make everything simple. Thanks for pointing it out. 

How do we want to proceed? There are other parts which require changes:

1. The `HookType` is no longer needed
2. Every implementation which has `TypeAware` in the name has to change
3. api.php has to change to remove the `HookType`

Could you take care of it or if you don't have time or do not want to doit we can discard your PR and I can fix it in another and obviously I'll give you props.

Let me know and thanks again

**Comment by szepeviktor** [comment]
Okay.

I let you remove part of your code.

**Comment by szepeviktor** [comment]
BTW I am happy that this package will be smaller!

**Pull request closed without merging**
