### PR TITLE
Fix Dispatcher Factory shouldn't be responsible of injecting the dispatcher

### PR DESCRIPTION
**Pull request by widoz**
Responsibility of Factory is to create an instance of something. 
The factory shouldn't be responsible to do anything else.

For the aforementioned reason the hookinjector procedure has been moved outside of the factory to the functional api

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could you suggest be a document or blog post to understand what a Dispatcher or a Factory is?

**Comment by widoz** [comment]
> Could you suggest me a document or blog post to understand what a Dispatcher or a Factory is?
I read the PSR-14 later day and I found that `Dispatcher` in this case is the wrong name, what we are building here are `Listeners` and I already have a PR improve naming here https://github.com/widoz/hooks-interfaces/pull/6 which I'll port to wp-hooks and hooks-collection later on (still need to refine something).

Anyway in this case the correct name should be `Listener Factory`.

Here some info: 

PSR-14: Event Dispatcher
https://www.php-fig.org/psr/psr-14/

Factory and Factory Method
https://github.com/domnikl/DesignPatternsPHP/tree/master/Creational/SimpleFactory
https://github.com/domnikl/DesignPatternsPHP/tree/master/Creational/FactoryMethod

At the end the Dispatcher/Listener Factory it's just a factory.
Factory is necessary to lazy instantiate the Dispatcher/Listener becase dev want to create hooks inside methods at runtime.

**Comment by szepeviktor** [comment]
>  Factory is necessary to lazy instantiate the Dispatcher/Listener becase dev want to create hooks inside methods at runtime.

Thank you!

So a Factory is a function invoking another function.

**Comment by widoz** [comment]
> So a Factory is a function invoking another function.

Can be a class with a method or a function within a container depends where you have to use it but basically any callable can be a factory which returns an instance of something.

For example https://3v4l.org/0jPiE even if usually the Factory is a class when injected into a constructor https://3v4l.org/C2Tup if used with containers instead them are generally used to share services within your application to not create everytime a new instance of a class since for a service will only be memory consuming.

**Pull request merged**
