### PR TITLE
Introduce WpHook Interface

### PR DESCRIPTION
**Pull request by widoz**

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is a Psalm exception.

Many projects have the issue of using Interface as typehint and providing an implementation.

What do you think about it?

```diff
diff --git a/src/Hook/WpHookInjector.php b/src/Hook/WpHookInjector.php
index 2c3f6e3..ddb9f4b 100644
--- a/src/Hook/WpHookInjector.php
+++ b/src/Hook/WpHookInjector.php
@@ -15,6 +15,7 @@ namespace Widoz\WpHooks\Hook;
 use Widoz\Hooks\Dispatch\HookDispatcher;
 use Widoz\Hooks\Hook\Hook;
 use Widoz\Hooks\Hook\HookInjector;
+use Widoz\WpHooks\Hook\WpHook;

 /**
  * Class WpHookInjector
@@ -28,6 +29,7 @@ class WpHookInjector implements HookInjector
      */
     public function addHook(Hook $hook, HookDispatcher $hookDispatcher): void
     {
+        \assert($hook instanceof WpHook);
         \add_filter(
             $hook->name(),
             $hookDispatcher,
diff --git a/src/Remover/WpHookRemover.php b/src/Remover/WpHookRemover.php
index 979ce1d..a67257f 100644
--- a/src/Remover/WpHookRemover.php
+++ b/src/Remover/WpHookRemover.php
@@ -15,6 +15,7 @@ namespace Widoz\WpHooks\Remover;
 use Widoz\Hooks\Dispatch\HookDispatcher;
 use Widoz\Hooks\Hook\Hook;
 use Widoz\Hooks\Remover\HookRemover;
+use Widoz\WpHooks\Hook\WpHook;

 /**
  * Class WpHookRemover
@@ -28,6 +29,7 @@ class WpHookRemover implements HookRemover
      */
     public function remove(Hook $hook, HookDispatcher $hookDispatcher): void
     {
+        \assert($hook instanceof WpHook);
         remove_filter($hook->name(), $hookDispatcher, $hook->priority());
     }
 }
```

**Comment by widoz** [comment]
Yeah, that's the problem to granularize too much I guess. 

I tried your suggestion to use `assert` but still getting the same error.
Btw according to the documentation https://www.php.net/manual/en/function.assert.php I would prefer to not introduce assertion as normal type check.

> Assertions should not be used for normal runtime operations like input parameter checks. As a rule of thumb your code should always be able to work correctly if assertion checking is not activated.

I think best way to solve this is to revert the interface to the previous.
Considering the https://github.com/widoz/hooks-interfaces/blob/develop/src/Remover/HookRemover.php which rely on `Hook` too I guess I'll introduce more problem than the one I'm trying to solve.

**Comment by szepeviktor** [comment]
Okay.

**Comment by widoz** [comment]
Any other idea?

**Comment by szepeviktor** [comment]
No, I do not develop OOP applications. I just use PHPStan and write very simple tools.

**Pull request merged**
